### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bonedaddy** [karalabe/ungx#1]
While reading the README file I came across this line:
```
Note, if you want to publish your dependency publicly, you'll need to rewrite all the package's internal imports to your fork paths (e.g. ungx --fork=github.com/myipfs/go-ipfs). and manually move the repository contents to $GOPATH/github.com/myipfs/go-ipfs.
```

Do I *ONLY* have to do that if I wish to publish the ungx'd go-ipfs package? If so then I assume that if I'm not going to do that, I can simply refer to the current directory (ie `go/src/github.com/go-ipfs`) as usual?

Thanks for this :D

**Comment by karalabe** [comment]
Yes, that should work too :) But I prefer to have a transformed code in a separate lib. Btw, if you need IPFS itself, I have an auto updating repo for that ;) https://github.com/ipsn/go-ipfs

**Comment by bonedaddy** [comment]
Awesome! That makes things much easier thank you :)
